server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/itheima?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver